"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"
import { useRouter, usePathname } from "next/navigation"

export type Language = "es" | "pt"

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

// Traducciones completas para ambos idiomas
const translations = {
  es: {
    "nav.services": "Servicios",
    "nav.portfolio": "Portafolio",
    "nav.process": "Proceso",
    "nav.testimonials": "Testimonios",
    "nav.blog": "Blog",
    "nav.contact": "Contacto",
    "nav.consultation": "Consulta Gratuita",
    "language.es": "Español",
    "language.pt": "Português",
    "language.switch": "Idioma: ES",
    "hero.title": "Convertimos visitantes en",
    "hero.subtitle":
      "Diseñamos landing pages que convierten hasta un 93% más que el promedio de la industria. Estrategia, diseño y psicología de conversión.",
    "hero.cta.primary": "Consulta Estratégica Gratuita",
    "hero.cta.secondary": "Ver Casos de Éxito",
    "hero.feature.1": "Diseño estratégico",
    "hero.feature.2": "Copywriting persuasivo",
    "hero.feature.3": "Animaciones atractivas",
    "hero.feature.4": "Optimización continua",
    "hero.trusted": "CONFÍAN EN NOSOTROS",
    "faq.title": "Preguntas frecuentes",
    "faq.subtitle": "Respuestas a las dudas más comunes sobre nuestros servicios de landing pages.",
    "faq.q1.question": "¿Cuánto tiempo tarda en crearse una landing page?",
    "faq.q1.answer":
      "El tiempo de desarrollo depende de la complejidad del proyecto. Nuestras landing pages esenciales se entregan en 7 días, las profesionales en 10 días y las premium en 14 días. Cada proyecto incluye una fase de revisión para asegurar que todo cumpla con tus expectativas.",
    "faq.q2.question": "¿Qué información necesitan para empezar?",
    "faq.q2.answer":
      "Para comenzar, necesitamos entender tus objetivos de negocio, tu audiencia objetivo, y cualquier material de marca existente (logo, colores, etc.). También es útil si puedes compartir ejemplos de landing pages que te gusten o referencias de la competencia. Con esta información, podemos crear una estrategia personalizada para tu proyecto.",
    "faq.q3.question": "¿Las landing pages incluyen hosting?",
    "faq.q3.answer":
      "Nuestros servicios no incluyen hosting por defecto, pero ofrecemos opciones de alojamiento como un servicio adicional. También podemos implementar la landing page en tu hosting existente o recomendarte proveedores confiables según tus necesidades específicas.",
    "faq.q4.question": "¿Ofrecen mantenimiento después del lanzamiento?",
    "faq.q4.answer":
      "Sí, ofrecemos planes de mantenimiento mensuales que incluyen actualizaciones de contenido, optimización continua y soporte técnico. También realizamos análisis periódicos de rendimiento para identificar oportunidades de mejora y maximizar tus conversiones a largo plazo.",
    "faq.q5.question": "¿Cómo miden el éxito de una landing page?",
    "faq.q5.answer":
      "Medimos el éxito a través de métricas clave como tasa de conversión, tiempo en página, tasa de rebote y retorno de inversión. Implementamos herramientas de análisis avanzadas para rastrear el comportamiento de los usuarios y optimizar continuamente el rendimiento de tu landing page.",
    "form.whatsapp": "WhatsApp (opcional)",
    "form.whatsapp.placeholder": "+34 600 000 000",
    "services.title": "Landing pages para cualquier objetivo",
    "services.subtitle": "Soluciones Estratégicas",
    "services.card1.title": "Landing Page de Ventas",
    "services.card1.description":
      "Diseñada para convertir visitantes en clientes, con un enfoque en la persuasión y el cierre de ventas.",
    "services.card1.feature1": "Copywriting persuasivo orientado a ventas",
    "services.card1.feature2": "Diseño de alta conversión",
    "services.card1.feature3": "Elementos de confianza y social proof",
    "services.card1.feature4": "Optimización para SEO y PPC",
    "services.card2.title": "Landing Page Lead Magnet",
    "services.card2.description":
      "Optimizada para capturar leads de calidad a través de contenido valioso y formularios estratégicos.",
    "services.card2.feature1": "Formularios optimizados para conversión",
    "services.card2.feature2": "Propuestas de valor claras y atractivas",
    "services.card2.feature3": "Integración con CRM y email marketing",
    "services.card2.feature4": "Seguimiento y nurturing automatizado",
    "services.card3.title": "Landing Page Evento",
    "services.card3.description":
      "Perfecta para promocionar eventos y maximizar registros con diseño enfocado en la acción inmediata.",
    "services.card3.feature1": "Cuenta regresiva y elementos de urgencia",
    "services.card3.feature2": "Agenda y detalles del evento",
    "services.card3.feature3": "Perfiles de speakers y participantes",
    "services.card3.feature4": "Integración con plataformas de eventos",
    "services.description": 
      "Diseñamos landing pages estratégicas que convierten visitantes en clientes, con un enfoque científico basado en psicología de conversión y análisis de datos.",
    "services.feature1": "Diseño UX/UI avanzado",
    "services.feature2": "Copywriting persuasivo",
    "services.feature3": "Optimización para conversión",
    "services.feature4": "Análisis de resultados",
    "services.button": "Ver detalles",
    "services.custom_solution": "¿Necesitas una solución personalizada?",
    "services.cta": "Agenda una consulta estratégica gratuita",
    "services.card1.alt": "Landing Page de Ventas",
    "services.card2.alt": "Landing Page Lead Magnet",
    "services.card3.alt": "Landing Page Evento",
    "services.card1.case_study.client": "TechSolutions Inc.",
    "services.card1.case_study.result": "+45% conversiones",
    "services.card2.case_study.client": "EcoFriendly",
    "services.card2.case_study.result": "320 leads en 1 semana",
    "services.card3.case_study.client": "EventMasters",
    "services.card3.case_study.result": "98% de registros completados",
    "authority.title": "Expertos en resultados",
    "authority.title_highlight": "resultados",
    "authority.subtitle": "Diseñamos landing pages estratégicas que maximizan conversiones y generan resultados medibles.",
    "authority.stat1.title": "de aumento en conversiones promedio",
    "authority.stat1.description": "Superamos consistentemente los benchmarks de la industria con estrategias de conversión avanzadas.",
    "authority.stat2.title": "landing pages creadas",
    "authority.stat2.description": "Experiencia comprobada en diversos sectores, desde SaaS y startups hasta e-commerce y servicios profesionales.",
    "authority.stat3.title": "de clientes que aumentan sus ventas",
    "authority.stat3.description": "Nuestro enfoque orientado a resultados garantiza un impacto real y medible en tu negocio.",
    "authority.success_badge": "Casos de éxito verificados",
    "authority.success_title": "Transformamos métricas en crecimiento real",
    "authority.success_subtitle": "Nuestras landing pages impulsan el crecimiento sostenible con estrategias probadas en startups de YCombinator y empresas SaaS.",
    "authority.feature1.title": "Optimización continua",
    "authority.feature1.description": "Mejoramos constantemente el rendimiento con pruebas A/B y análisis de datos.",
    "authority.feature2.title": "Enfoque centrado en el usuario",
    "authority.feature2.description": "Diseñamos experiencias que conectan con tu audiencia y generan acción.",
    "authority.cta": "Ver todos los casos de éxito",
    "authority.image1.alt": "Dashboard de resultados",
    "authority.image2.alt": "Análisis de conversión",
    "authority.conversion_label": "Conversión",
    "process.title": "Nuestro proceso probado para el éxito",
    "process.subtitle": "Un enfoque metódico que garantiza landing pages de alto rendimiento y resultados excepcionales.",
    "process.step1.title": "Estrategia & Investigación",
    "process.step1.description": "Analizamos tu audiencia, competencia y objetivos para crear una estrategia ganadora.",
    "process.step2.title": "Diseño & Copywriting",
    "process.step2.description": "Creamos diseños atractivos y textos persuasivos que conectan con tu audiencia.",
    "process.step3.title": "Desarrollo & Animaciones",
    "process.step3.description": "Implementamos tu landing page con código limpio y animaciones que capturan la atención.",
    "process.step4.title": "Pruebas & Optimización",
    "process.step4.description": "Realizamos pruebas A/B y optimizamos continuamente para maximizar conversiones.",
    "portfolio.title": "Casos de éxito que hablan por sí mismos",
    "portfolio.subtitle": "Descubre cómo hemos ayudado a empresas a aumentar sus conversiones con landing pages estratégicas.",
    "portfolio.button": "Ver todo el portafolio",
    "portfolio.item1.client": "TechSolutions Inc.",
    "portfolio.item1.type": "Landing Page de Ventas",
    "portfolio.item1.result": "45% más conversiones",
    "portfolio.item1.alt": "Landing Page de Ventas para TechSolutions Inc.",
    "portfolio.item2.client": "EcoFriendly",
    "portfolio.item2.type": "Landing Page Lead Magnet",
    "portfolio.item2.result": "320 leads en 1 semana",
    "portfolio.item2.alt": "Landing Page Lead Magnet para EcoFriendly",
    "portfolio.item3.client": "FinanceGrow",
    "portfolio.item3.type": "Landing Page de Ventas",
    "portfolio.item3.result": "67% más tiempo en página",
    "portfolio.item3.alt": "Landing Page de Ventas para FinanceGrow",
    "portfolio.item4.client": "EventMasters",
    "portfolio.item4.type": "Landing Page Evento",
    "portfolio.item4.result": "98% de registros completados",
    "portfolio.item4.alt": "Landing Page Evento para EventMasters",
    "portfolio.item5.client": "HealthPlus",
    "portfolio.item5.type": "Landing Page Lead Magnet",
    "portfolio.item5.result": "52% tasa de conversión",
    "portfolio.item5.alt": "Landing Page Lead Magnet para HealthPlus",
    "portfolio.item6.client": "TravelDreams",
    "portfolio.item6.type": "Landing Page de Ventas",
    "portfolio.item6.result": "3x ROI en campañas",
    "portfolio.item6.alt": "Landing Page de Venta para TravelDreams",
    "testimonials.title": "Lo que dicen nuestros clientes",
    "testimonials.subtitle": "Historias reales de clientes que transformaron sus resultados con nuestras landing pages.",
    "testimonials.prev_button": "Testimonio anterior",
    "testimonials.next_button": "Siguiente testimonio",
    "testimonials.nav_button": "Ir al testimonio {index}",
    "testimonials.item1.name": "Carlos Rodríguez",
    "testimonials.item1.company": "TechSolutions Inc.",
    "testimonials.item1.text": 
      "Trabajar con Hero&Framer Studio fue una experiencia excepcional. Entendieron perfectamente nuestras necesidades y crearon una landing page que superó todas nuestras expectativas. Las conversiones aumentaron un 45% en el primer mes.",
    "testimonials.item1.result": "45% más conversiones",
    "testimonials.item1.alt": "Foto de Carlos Rodríguez",
    "testimonials.item2.name": "Laura Martínez",
    "testimonials.item2.company": "EcoFriendly",
    "testimonials.item2.text": 
      "Nuestra campaña de lead magnet fue un éxito rotundo gracias a la landing page diseñada por Hero&Framer Studio. El diseño atractivo y el copywriting persuasivo nos ayudaron a captar más de 300 leads cualificados en una semana.",
    "testimonials.item2.result": "320 leads en 1 semana",
    "testimonials.item2.alt": "Foto de Laura Martínez",
    "testimonials.item3.name": "Miguel Sánchez",
    "testimonials.item3.company": "FinanceGrow",
    "testimonials.item3.text": 
      "La atención al detalle y el enfoque estratégico de Hero&Framer Studio marcaron la diferencia en nuestro proyecto. La landing page no solo es visualmente impresionante, sino que también convierte a un nivel que nunca habíamos visto antes.",
    "testimonials.item3.result": "67% más tiempo en página",
    "testimonials.item3.alt": "Foto de Miguel Sánchez",
    "pricing.title": "Planes que se adaptan a tu negocio",
    "pricing.subtitle": "Soluciones a medida para maximizar tus conversiones, sin importar el tamaño de tu empresa.",
    "pricing.popular_label": "Más popular",
    "pricing.button": "Seleccionar plan",
    "pricing.plan1.name": "Esencial",
    "pricing.plan1.description": "Para profesionales independientes",
    "pricing.plan1.features.1": "1 Landing Page",
    "pricing.plan1.features.2": "Diseño responsive",
    "pricing.plan1.features.3": "Copywriting persuasivo",
    "pricing.plan1.features.4": "Formulario de contacto",
    "pricing.plan1.features.5": "Optimización SEO básica",
    "pricing.plan1.features.6": "Entrega en 7 días",
    "pricing.plan2.name": "Profesional",
    "pricing.plan2.description": "Para pequeñas empresas",
    "pricing.plan2.features.1": "1 Landing Page",
    "pricing.plan2.features.2": "Diseño responsive premium",
    "pricing.plan2.features.3": "Copywriting avanzado",
    "pricing.plan2.features.4": "Integración con CRM",
    "pricing.plan2.features.5": "Animaciones personalizadas",
    "pricing.plan2.features.6": "Optimización SEO completa",
    "pricing.plan2.features.7": "A/B Testing",
    "pricing.plan2.features.8": "Entrega en 10 días",
    "pricing.plan3.name": "Premium",
    "pricing.plan3.description": "Para medianas empresas",
    "pricing.plan3.features.1": "1 Landing Page compleja",
    "pricing.plan3.features.2": "Diseño responsive premium+",
    "pricing.plan3.features.3": "Copywriting por expertos",
    "pricing.plan3.features.4": "Integraciones avanzadas",
    "pricing.plan3.features.5": "Animaciones personalizadas",
    "pricing.plan3.features.6": "Optimización SEO avanzada",
    "pricing.plan3.features.7": "A/B Testing múltiple",
    "pricing.plan3.features.8": "Análisis de conversión",
    "pricing.plan3.features.9": "Entrega en 14 días",
    "contact.title": "¿Listo para empezar tu proyecto?",
    "contact.subtitle": "Cuéntanos sobre tu proyecto y te ayudaremos a elegir la mejor solución para tus necesidades.",
    "contact.step1.title": "¿Cómo te llamas?",
    "contact.step1.placeholder": "Tu nombre completo",
    "contact.step2.title": "¿Cuál es tu correo electrónico?",
    "contact.step2.placeholder": "tu@email.com",
    "contact.step3.title": "¿Para qué empresa trabajas?",
    "contact.step3.placeholder": "Nombre de tu empresa",
    "contact.step5.title": "¿Qué plan te interesa?",
    "contact.step6.title": "¿Algo más que quieras contarnos?",
    "contact.step6.placeholder": "Cuéntanos más sobre tu proyecto...",
    "contact.button.prev": "Anterior",
    "contact.button.next": "Siguiente",
    "contact.button.submit": "Enviar",
    "contact.button.submitting": "Enviando...",
    "contact.button.reset": "Enviar otro mensaje",
    "contact.success.title": "¡Mensaje enviado con éxito!",
    "contact.success.message": "Gracias por contactarnos. Nos pondremos en contacto contigo lo antes posible.",
    "contact.plan1.name": "Esencial",
    "contact.plan1.description": "Para profesionales independientes",
    "contact.plan2.name": "Profesional",
    "contact.plan2.description": "Para pequeñas empresas",
    "contact.plan3.name": "Premium",
    "contact.plan3.description": "Para medianas empresas",
    "cta.label": "Impulsa tu negocio ahora",
    "cta.title": "¿Listo para multiplicar tus conversiones?",
    "cta.title_highlight": "multiplicar",
    "cta.subtitle": 
      "Agenda una consulta estratégica gratuita y descubre cómo podemos transformar tu landing page en una máquina de conversión que genere resultados excepcionales.",
    "cta.feature1.title": "Análisis de tu landing page actual",
    "cta.feature1.description": "Identificamos oportunidades de mejora y puntos débiles.",
    "cta.feature2.title": "Estrategia personalizada",
    "cta.feature2.description": "Desarrollamos un plan adaptado a tus objetivos específicos.",
    "cta.feature3.title": "Proyección de resultados",
    "cta.feature3.description": "Estimamos el impacto potencial en tus métricas clave.",
    "cta.button": "Reservar Consulta Estratégica",
    "cta.note": "Sin compromiso. Plazas limitadas cada semana.",
    "cta.domain": "hero-framer-studio.com",
    "cta.conversion_label": "Tasa de conversión",
    "cta.conversion_value": "+93%",
    "footer.description": 
      "Agencia especializada en diseño de landing pages convertibles y lead magnets. Transformamos visitantes en clientes con diseños estratégicos y persuasivos.",
    "footer.quick_links": "Enlaces rápidos",
    "footer.quick_links.services": "Servicios",
    "footer.quick_links.portfolio": "Portafolio",
    "footer.quick_links.process": "Proceso",
    "footer.quick_links.testimonials": "Testimonios",
    "footer.quick_links.blog": "Blog",
    "footer.services": "Servicios",
    "footer.services.sales": "Landing Page de Ventas",
    "footer.services.lead_magnet": "Landing Page Lead Magnet",
    "footer.services.event": "Landing Page Evento",
    "footer.services.conversion": "Optimización de Conversión",
    "footer.services.copywriting": "Copywriting Persuasivo",
    "footer.contact": "Contacto",
    "footer.contact.address": "Calle Innovación 123, 28001 Madrid, España",
    "footer.contact.phone": "+34 91 123 45 67",
    "footer.contact.email": "info@heroframer.com",
    "footer.copyright": "© {currentYear} Hero&Framer Studio. Todos los derechos reservados.",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos y Condiciones",
    "footer.cookies": "Cookies",
    "footer.social.facebook": "Facebook",
    "footer.social.twitter": "Twitter",
    "footer.social.instagram": "Instagram",
    "footer.social.linkedin": "LinkedIn",
    "whatsapp.accessibility": "Contactar por WhatsApp",
    "cookie_consent.message": 
      "Utilizamos cookies para mejorar tu experiencia en nuestro sitio web. Al continuar navegando, aceptas nuestra",
    "cookie_consent.policy": "política de cookies",
    "cookie_consent.reject": "Rechazar",
    "cookie_consent.accept": "Aceptar",
  },
  pt: {
    "nav.services": "Serviços",
    "nav.portfolio": "Portfólio",
    "nav.process": "Processo",
    "nav.testimonials": "Depoimentos",
    "nav.blog": "Blog",
    "nav.contact": "Contato",
    "nav.consultation": "Consulta Gratuita",
    "language.es": "Español",
    "language.pt": "Português",
    "language.switch": "Idioma: PT",
    "hero.title": "Convertemos visitantes em",
    "hero.subtitle":
      "Projetamos landing pages que convertem até 93% mais do que a média do setor. Estratégia, design e psicologia de conversão.",
    "hero.cta.primary": "Consulta Estratégica Gratuita",
    "hero.cta.secondary": "Ver Casos de Sucesso",
    "hero.feature.1": "Design estratégico",
    "hero.feature.2": "Copywriting persuasivo",
    "hero.feature.3": "Animações atraentes",
    "hero.feature.4": "Otimização contínua",
    "hero.trusted": "CONFIAM EM NÓS",
    "faq.title": "Perguntas frequentes",
    "faq.subtitle": "Respostas às dúvidas mais comuns sobre nossos serviços de landing pages.",
    "faq.q1.question": "Quanto tempo leva para criar uma landing page?",
    "faq.q1.answer":
      "O tempo de desenvolvimento depende da complexidade do projeto. Nossas landing pages essenciais são entregues em 7 dias, as profissionais em 10 dias e as premium em 14 dias. Cada projeto inclui uma fase de revisão para garantir que tudo atenda às suas expectativas.",
    "faq.q2.question": "Que informações vocês precisam para começar?",
    "faq.q2.answer":
      "Para começar, precisamos entender seus objetivos de negócios, seu público-alvo e qualquer material de marca existente (logotipo, cores, etc.). Também é útil se você puder compartilhar exemplos de landing pages que goste ou referências da concorrência. Com essas informações, podemos criar uma estratégia personalizada para seu projeto.",
    "faq.q3.question": "As landing pages incluem hospedagem?",
    "faq.q3.answer":
      "Nossos serviços não incluem hospedagem por padrão, mas oferecemos opções de hospedagem como um serviço adicional. Também podemos implementar a landing page em sua hospedagem existente ou recomendar provedores confiáveis conforme suas necessidades específicas.",
    "faq.q4.question": "Vocês oferecem manutenção após o lançamento?",
    "faq.q4.answer":
      "Sim, oferecemos planos de manutenção mensais que incluem atualizações de conteúdo, otimização contínua e suporte técnico. Também realizamos análises periódicas de desempenho para identificar oportunidades de melhoria e maximizar suas conversões a longo prazo.",
    "faq.q5.question": "Como vocês medem o sucesso de uma landing page?",
    "faq.q5.answer":
      "Medimos o sucesso por meio de métricas-chave como taxa de conversão, tempo na página, taxa de rejeição e retorno sobre investimento. Implementamos ferramentas avançadas de análise para rastrear o comportamento dos usuários e otimizar continuamente o desempenho da sua landing page.",
    "form.whatsapp": "WhatsApp (opcional)",
    "form.whatsapp.placeholder": "+55 11 00000 0000",
    "services.title": "Landing pages para cualquier objetivo",
    "services.subtitle": "Soluções Estratégicas",
    "services.card1.title": "Landing Page de Vendas",
    "services.card1.description":
      "Projetada para converter visitantes em clientes, com foco em persuasão e fechamento de vendas.",
    "services.card1.feature1": "Copywriting persuasivo orientado para vendas",
    "services.card1.feature2": "Design de alta conversão",
    "services.card1.feature3": "Elementos de confianza e prova social",
    "services.card1.feature4": "Otimização para SEO e PPC",
    "services.card2.title": "Landing Page Lead Magnet",
    "services.card2.description":
      "Otimizada para capturar leads qualificados por meio de conteúdo valioso e formulários estratégicos.",
    "services.card2.feature1": "Formulários otimizados para conversão",
    "services.card2.feature2": "Propostas de valor claras e atraentes",
    "services.card2.feature3": "Integração com CRM e email marketing",
    "services.card2.feature4": "Acompanhamento e nutrição automatizados",
    "services.card3.title": "Landing Page Evento",
    "services.card3.description":
      "Perfeita para promover eventos e maximizar inscrições com design focado na ação imediata.",
    "services.card3.feature1": "Contagem regressiva e elementos de urgência",
    "services.card3.feature2": "Agenda e detalhes do evento",
    "services.card3.feature3": "Perfis de palestrantes e participantes",
    "services.card3.feature4": "Integração com plataformas de eventos",
    "services.description": 
      "Projetamos landing pages estratégicas que convertem visitantes em clientes, com uma abordagem científica baseada em psicologia de conversão e análise de dados.",
    "services.feature1": "Design UX/UI avançado",
    "services.feature2": "Copywriting persuasivo",
    "services.feature3": "Otimização para conversão",
    "services.feature4": "Análise de resultados",
    "services.button": "Ver detalhes",
    "services.custom_solution": "Precisa de uma solução personalizada?",
    "services.cta": "Agende uma consulta estratégica gratuita",
    "services.card1.alt": "Landing Page de Vendas",
    "services.card2.alt": "Landing Page Lead Magnet",
    "services.card3.alt": "Landing Page Evento",
    "services.card1.case_study.client": "TechSolutions Inc.",
    "services.card1.case_study.result": "+45% conversões",
    "services.card2.case_study.client": "EcoFriendly",
    "services.card2.case_study.result": "320 leads em 1 semana",
    "services.card3.case_study.client": "EventMasters",
    "services.card3.case_study.result": "98% de inscripciones completadas",
    "authority.title": "Especialistas em resultados",
    "authority.title_highlight": "resultados",
    "authority.subtitle": "Projetamos landing pages estratégicas que maximizam conversões e geram resultados mensuráveis.",
    "authority.stat1.title": "de aumento nas conversões em média",
    "authority.stat1.description": "Superamos consistentemente os benchmarks do setor com estratégias avançadas de conversão.",
    "authority.stat2.title": "landing pages criadas",
    "authority.stat2.description": "Experiência comprovada em diversos setores, de SaaS e startups a e-commerce e serviços profissionais.",
    "authority.stat3.title": "de clientes que aumentan sus ventas",
    "authority.stat3.description": "Nossa abordagem orientada a resultados garante um impacto real e mensurável no seu negócio.",
    "authority.success_badge": "Casos de sucesso verificados",
    "authority.success_title": "Transformamos métricas em crescimento real",
    "authority.success_subtitle": "Nossas landing pages impulsionam o crescimento sustentável com estratégias comprovadas em startups da YCombinator e empresas SaaS.",
    "authority.feature1.title": "Otimização contínua",
    "authority.feature1.description": "Melhoramos constantemente o desempenho com testes A/B e análise de dados.",
    "authority.feature2.title": "Abordagem centrada no usuário",
    "authority.feature2.description": "Projetamos experiências que conectan com seu público e geram ação.",
    "authority.cta": "Ver todos los casos de éxito",
    "authority.image1.alt": "Painel de resultados",
    "authority.image2.alt": "Análise de conversão",
    "authority.conversion_label": "Conversão",
    "process.title": "Nosso processo comprovado para o sucesso",
    "process.subtitle": "Uma abordagem metódica que garante landing pages de alto desempenho e resultados excepcionais.",
    "process.step1.title": "Estratégia & Pesquisa",
    "process.step1.description": "Analisamos seu público, concorrência e objetivos para criar uma estratégia vencedora.",
    "process.step2.title": "Design & Copywriting",
    "process.step2.description": "Criamos designs atraentes e textos persuasivos que conectan com seu público.",
    "process.step3.title": "Desenvolvimento & Animações",
    "process.step3.description": "Implementamos sua landing page com código limpo e animações que capturam a atenção.",
    "process.step4.title": "Testes & Otimização",
    "process.step4.description": "Realizamos testes A/B e otimizamos continuamente para maximizar conversões.",
    "portfolio.title": "Casos de sucesso que falam por si mesmos",
    "portfolio.subtitle": "Descubra como ajudamos empresas a aumentar suas conversões com landing pages estratégicas.",
    "portfolio.button": "Ver todo o portfólio",
    "portfolio.item1.client": "TechSolutions Inc.",
    "portfolio.item1.type": "Landing Page de Vendas",
    "portfolio.item1.result": "45% mais conversões",
    "portfolio.item1.alt": "Landing Page de Vendas para TechSolutions Inc.",
    "portfolio.item2.client": "EcoFriendly",
    "portfolio.item2.type": "Landing Page Lead Magnet",
    "portfolio.item2.result": "320 leads em 1 semana",
    "portfolio.item2.alt": "Landing Page Lead Magnet para EcoFriendly",
    "portfolio.item3.client": "FinanceGrow",
    "portfolio.item3.type": "Landing Page de Vendas",
    "portfolio.item3.result": "67% mais tempo na página",
    "portfolio.item3.alt": "Landing Page de Vendas para FinanceGrow",
    "portfolio.item4.client": "EventMasters",
    "portfolio.item4.type": "Landing Page Evento",
    "portfolio.item4.result": "98% de inscripciones completadas",
    "portfolio.item4.alt": "Landing Page Evento para EventMasters",
    "portfolio.item5.client": "HealthPlus",
    "portfolio.item5.type": "Landing Page Lead Magnet",
    "portfolio.item5.result": "52% taxa de conversão",
    "portfolio.item5.alt": "Landing Page Lead Magnet para HealthPlus",
    "portfolio.item6.client": "TravelDreams",
    "portfolio.item6.type": "Landing Page de Vendas",
    "portfolio.item6.result": "3x ROI em campanhas",
    "portfolio.item6.alt": "Landing Page de Vendas para TravelDreams",
    "testimonials.title": "O que dizem nossos clientes",
    "testimonials.subtitle": "Histórias reais de clientes que transformaram seus resultados com nossas landing pages.",
    "testimonials.prev_button": "Depoimento anterior",
    "testimonials.next_button": "Próximo depoimento",
    "testimonials.nav_button": "Ir para o depoimento {index}",
    "testimonials.item1.name": "Carlos Rodríguez",
    "testimonials.item1.company": "TechSolutions Inc.",
    "testimonials.item1.text": 
      "Trabalhar com a Hero&Framer Studio foi uma experiência excepcional. Eles entenderam perfeitamente nossas necessidades e criaram uma landing page que superou todas as nossas expectativas. As conversões aumentaram 45% no primeiro mês.",
    "testimonials.item1.result": "45% mais conversões",
    "testimonials.item1.alt": "Foto de Carlos Rodríguez",
    "testimonials.item2.name": "Laura Martínez",
    "testimonials.item2.company": "EcoFriendly",
    "testimonials.item2.text": 
      "Nossa campanha de lead magnet foi um sucesso total graças à landing page projetada pela Hero&Framer Studio. O design atraente e o copywriting persuasivo nos ajudaram a capturar mais de 300 leads qualificados em uma semana.",
    "testimonials.item2.result": "320 leads em 1 semana",
    "testimonials.item2.alt": "Foto de Laura Martínez",
    "testimonials.item3.name": "Miguel Sánchez",
    "testimonials.item3.company": "FinanceGrow",
    "testimonials.item3.text": 
      "A atenção aos detalhes e a abordagem estratégica da Hero&Framer Studio fizeram toda a diferença em nosso projeto. A landing page não é apenas visualmente impressionante, mas também converte em um nível que nunca vimos antes.",
    "testimonials.item3.result": "67% mais tempo na página",
    "testimonials.item3.alt": "Foto de Miguel Sánchez",
    "pricing.title": "Planos que se adaptam ao seu negócio",
    "pricing.subtitle": "Soluções sob medida para maximizar suas conversões, independentemente do tamanho da sua empresa.",
    "pricing.popular_label": "Mais popular",
    "pricing.button": "Selecionar plano",
    "pricing.plan1.name": "Essencial",
    "pricing.plan1.description": "Para profissionais autônomos",
    "pricing.plan1.features.1": "1 Landing Page",
    "pricing.plan1.features.2": "Design responsivo",
    "pricing.plan1.features.3": "Copywriting persuasivo",
    "pricing.plan1.features.4": "Formulário de contato",
    "pricing.plan1.features.5": "Otimização SEO básica",
    "pricing.plan1.features.6": "Entrega em 7 dias",
    "pricing.plan2.name": "Profissional",
    "pricing.plan2.description": "Para pequenas empresas",
    "pricing.plan2.features.1": "1 Landing Page",
    "pricing.plan2.features.2": "Design responsivo premium",
    "pricing.plan2.features.3": "Copywriting avançado",
    "pricing.plan2.features.4": "Integração com CRM",
    "pricing.plan2.features.5": "Animações personalizadas",
    "pricing.plan2.features.6": "Otimização SEO completa",
    "pricing.plan2.features.7": "Teste A/B",
    "pricing.plan2.features.8": "Entrega em 10 dias",
    "pricing.plan3.name": "Premium",
    "pricing.plan3.description": "Para empresas de médio porte",
    "pricing.plan3.features.1": "1 Landing Page complexa",
    "pricing.plan3.features.2": "Design responsivo premium+",
    "pricing.plan3.features.3": "Copywriting por especialistas",
    "pricing.plan3.features.4": "Integrações avançadas",
    "pricing.plan3.features.5": "Animações personalizadas",
    "pricing.plan3.features.6": "Otimização SEO avançada",
    "pricing.plan3.features.7": "Teste A/B múltiplo",
    "pricing.plan3.features.8": "Análise de conversão",
    "pricing.plan3.features.9": "Entrega en 14 días",
    "contact.title": "Pronto para começar seu projeto?",
    "contact.subtitle": "Conte-nos sobre seu projeto e ajudaremos você a escolher a melhor solução para suas necessidades.",
    "contact.step1.title": "Qual é o seu nome?",
    "contact.step1.placeholder": "Seu nome completo",
    "contact.step2.title": "Qual é o seu e-mail?",
    "contact.step2.placeholder": "seu@email.com",
    "contact.step3.title": "Para qual empresa você trabalha?",
    "contact.step3.placeholder": "Nome da sua empresa",
    "contact.step5.title": "Qual plano lhe interessa?",
    "contact.step6.title": "Algo mais que você gostaria de nos contar?",
    "contact.step6.placeholder": "Conte-nos mais sobre seu projeto...",
    "contact.button.prev": "Anterior",
    "contact.button.next": "Próximo",
    "contact.button.submit": "Enviar",
    "contact.button.submitting": "Enviando...",
    "contact.button.reset": "Enviar outra mensagem",
    "contact.success.title": "Mensagem enviada com sucesso!",
    "contact.success.message": "Obrigado por entrar em contato. Entraremos em contato com você o mais breve possível.",
    "contact.plan1.name": "Essencial",
    "contact.plan1.description": "Para profissionais autônomos",
    "contact.plan2.name": "Profissional",
    "contact.plan2.description": "Para pequenas empresas",
    "contact.plan3.name": "Premium",
    "contact.plan3.description": "Para empresas de médio porte",
    "cta.label": "Impulsione seu negócio agora",
    "cta.title": "Pronto para multiplicar suas conversões?",
    "cta.title_highlight": "multiplicar",
    "cta.subtitle": 
      "Agende uma consulta estratégica gratuita e descubra como podemos transformar sua landing page em uma máquina de conversão que gera resultados excepcionais.",
    "cta.feature1.title": "Análise da sua landing page atual",
    "cta.feature1.description": "Identificamos oportunidades de melhoria e pontos fracos.",
    "cta.feature2.title": "Estratégia personalizada",
    "cta.feature2.description": "Desenvolvemos um plano adaptado aos seus objetivos específicos.",
    "cta.feature3.title": "Projeção de resultados",
    "cta.feature3.description": "Estimamos o impacto potencial nas suas métricas-chave.",
    "cta.button": "Agendar Consulta Estratégica",
    "cta.note": "Sem compromisso. Vagas limitadas a cada semana.",
    "cta.domain": "hero-framer-studio.com",
    "cta.conversion_label": "Taxa de conversão",
    "cta.conversion_value": "+93%",
    "footer.description": 
      "Agência especializada em design de landing pages conversíveis e lead magnets. Transformamos visitantes em clientes com designs estratégicos e persuasivos.",
    "footer.quick_links": "Links rápidos",
    "footer.quick_links.services": "Serviços",
    "footer.quick_links.portfolio": "Portfólio",
    "footer.quick_links.process": "Processo",
    "footer.quick_links.testimonials": "Depoimentos",
    "footer.quick_links.blog": "Blog",
    "footer.services": "Serviços",
    "footer.services.sales": "Landing Page de Vendas",
    "footer.services.lead_magnet": "Landing Page Lead Magnet",
    "footer.services.event": "Landing Page Evento",
    "footer.services.conversion": "Otimização de Conversão",
    "footer.services.copywriting": "Copywriting Persuasivo",
    "footer.contact": "Contato",
    "footer.contact.address": "Rua Inovação 123, 28001 Lisboa, Portugal",
    "footer.contact.phone": "+351 21 123 45 67",
    "footer.contact.email": "info@heroframer.com",
    "footer.copyright": "© {currentYear} Hero&Framer Studio. Todos os direitos reservados.",
    "footer.privacy": "Política de Privacidade",
    "footer.terms": "Termos e Condições",
    "footer.cookies": "Cookies",
    "footer.social.facebook": "Facebook",
    "footer.social.twitter": "Twitter",
    "footer.social.instagram": "Instagram",
    "footer.social.linkedin": "LinkedIn",
    "whatsapp.accessibility": "Contactar pelo WhatsApp",
    "cookie_consent.message": 
      "Utilizamos cookies para melhorar sua experiência em nosso site. Ao continuar navegando, você aceita nossa",
    "cookie_consent.policy": "política de cookies",
    "cookie_consent.reject": "Rejeitar",
    "cookie_consent.accept": "Aceitar",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("es")
  const router = useRouter()
  const pathname = usePathname()

  // Función para cambiar el idioma y actualizar la URL
  const changeLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage)

    // Actualizar la URL con el código de idioma
    if (pathname) {
      const currentPath = pathname || "/"
      const basePath = currentPath.replace(/^\/(es|pt)/, "")
      router.push(`/${newLanguage}${basePath}`)
    }
  }

  // Detectar el idioma de la URL al cargar
  useEffect(() => {
    if (pathname) {
      const match = pathname.match(/^\/(es|pt)/)
      if (match && (match[1] === "es" || match[1] === "pt")) {
        setLanguage(match[1] as Language)
      }
    }
  }, [pathname])

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>{children}</LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}